### ISSUE TITLE
How can i config this addon?

### ISSUE THREAD

**Issue by embynick** [vitorazevedo/HealersSerenity#1]
How can i config this addon?

**Comment by vitorazevedo** [comment]
The current beta version of this addon supports a set of predefined spells for Druids. Soon, we'll add a feature to customize spells for all healers. Currently, it's mainly for healers to heal themselves, but it will soon support healing in parties and raids.

Here is the current binding:
```
  DRUID = {
    LeftClickSpell = "Regrowth",
    RightClickSpell = "Cenarion Ward",
    ShiftLeftClickSpell = "Rejuvenation",
    ShiftRightClickSpell = "Lifebloom",
    AltLeftClickSpell = "Swiftmend",
    AltRightClickSpell = "Ironbark",
    CtrlLeftClickSpell = "Nature's Cure",
    CtrlRightClickSpell = "Adaptive Swarm"
  },
```
